version: '2'
services:
  app:
    # build: .
    image: registry.cn-hangzhou.aliyuncs.com/sino_logs/sino_logs
    depends_on:
    - mysql
    volumes:
    - /home/Service
    ports:
    - "8080:2018"
    environment:
    - KEYMETRICS_PUBLIC=m5ds5q2bd7pxghe
    - KEYMETRICS_SECRET=qzi785bx94nsysk
    links:
    - mysql:mysqls

